In [1]:
import numpy as np

# Determinant Functions of 2x2 and 3x3 Matrices

This function will solve for the determinant of a 2x2 square matrix

In [2]:
def solve_2by2(input_array):
    # Solve a determinant of a 2x2 matrix
    a = input_array[0, 0]
    b = input_array[0, 1]
    c = input_array[1, 0]
    d = input_array[1, 1]
    
    return a*d-b*c

Create a random 2x2 matrix and solve for its determinant

In [3]:
# control randomization
np.random.seed(123)

# create 2x2 matrix
A = np.random.randint(50, size=(2,2))
print(A)

# solve for determinant with created function
print('Using created function\n ', solve_2by2(A))

# solve for determinant using numpy function to verify
print('Using Numpy function\n ', np.linalg.det(A))

[[45  2]
 [28 34]]
Using created function
  1474
Using Numpy function
  1473.9999999999998


<hr>

This function will solve for the determinant of a 3x3 square matrix

In [4]:
def solve_3by3(input_array):
    # Solve a determinant of a 3x3 matrix
    a = input_array[0, 0]
    b = input_array[0, 1]
    c = input_array[0, 2]
    d = input_array[1, 0]
    e = input_array[1, 1]
    f = input_array[1, 2]
    g = input_array[2, 0]
    h = input_array[2, 1]
    i = input_array[2, 2]
    
    return (a*(e*i - f*h)) - (b*(d*i - f*g)) + (c*(d*h - e*g))

In [5]:
# control randomization
np.random.seed(123)

# create 2x2 matrix
B = np.random.randint(50, size=(3,3))
print(B)

# solve for determinant with created function
print('Using created function: ', solve_3by3(B))

# solve for determinant using numpy function to verify
print('Using Numpy function: ', np.linalg.det(B))

[[45  2 28]
 [34 38 17]
 [19 42 22]]
Using created function:  24408
Using Numpy function:  24408.000000000015
